CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS addresses(
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	id_api TEXT NOT NULL,
	name VARCHAR(255) NOT NULL,
	lat FLOAT8 NOT NULL,
	lon FLOAT8 NOT NULL
);
