CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS roles(
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users(
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	login VARCHAR(255) NOT NULL UNIQUE,
	password TEXT NOT NULL,
	role_id UUID REFERENCES roles(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS sessions(
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	user_id UUID REFERENCES users(id) ON DELETE CASCADE,
	token TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
